#!/bin/bash

SCRIPTS=$1/src/require.src
TEMPLATE=$1/src/index.html.template
INDEX=$1/index.html

cp $TEMPLATE $INDEX
cat $SCRIPTS | awk -f scripts.awk > scripts.tmp

sed -e "/::SCRIPTS::/r scripts.tmp" -e "/::SCRIPTS::/d" $TEMPLATE > $INDEX

rm scripts.tmp
